name: Build and push image

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
#  schedule:
#    - cron: '43 5 * * 0'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        # Merge ~ push.
        #if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: rlespinasse/github-slug-action@4.2.3

      - name: Build and push
        uses: docker/build-push-action@v3
#        if: ${{ github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'build')) }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          # Only push on tags or main branch
          push: ${{ github.event_name == 'push' }}
          tags: workadventure/playwright-synthetic-monitoring:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
          cache-from: |
            type=registry,ref=workadventure/playwright-synthetic-monitoring:${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
            type=registry,ref=workadventure/playwright-synthetic-monitoring:develop
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
